server:
  port: 8070
  servlet:
    context-path: /api/borrow

spring:
  application:
    name: borrow-service
  profiles:
      active: dev
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# JWT secret key – must match the same key used in auth-service
jwt:
  secret: ${JWT_SECRET}
  # noinspection SpringBootApplicationYaml
  expiration: ${JWT_EXPIRATION}

# Feign client log level
logging:
  level:
    com.fptdemo.borrowservice: DEBUG
    com.fptdemo.borrowservice.client.BookClient: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      # Make actuator accessible at /api/borrow/actuator/** (same context-path as the app)
#      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always

